#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RottonTomatoesApp.Resource", IsApplication=true)]

namespace RottonTomatoesApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int androidcolors = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int blue = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int darkblue = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int darkgreen = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int darkorange = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int darkpurple = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int darkred = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int green = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int movietitleblue = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int orange = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int purple = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int red = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int large_movie_poster = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ListItemMovieSelector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int rotton_rating = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int small_movie_poster = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int testimage = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000a
			public const int BoxOfficeMoviesList = 2131165194;
			
			// aapt resource value: 0x7f070005
			public const int MovieCast = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int MovieDate = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int MovieImage = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int MovieRating = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int MovieScore = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int MovieTime = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int MovieTitle = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int MovieTomato = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int RightArrow = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int dsds = 2131165195;
			
			// aapt resource value: 0x7f070000
			public const int headerrr = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListItemHeader = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItemMovie = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Movie = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
